(define (domain taxi_domain1)
    (:requirements :adl :typing :negative-preconditions :action-costs)
    (:types passenger - object  location - object)

    (:predicates 
        (road ?l1 ?l2 - location)
        (trafficLight ?l1 ?l2 - location)
        (taxiAt ?l - location)
        (passengerAt ?p - passenger ?l - location)
        (requestFrom ?p - passenger ?l - location)
        (requestTo ?p - passenger ?l - location)
        (onTaxi ?p - passenger)
        (congested ?l - location)
        (rechargeStation ?l - location)
    )
    
    (:functions 
        (total-cost)
        (distance ?l1 ?l2 - location)
        (cost-per-distance)
        (batteryLevel)
    )
    (:action move
        :parameters (?l1 ?l2 - location)
        :precondition(and(taxiAt ?l1)
                        (road ?l1 ?l2)
                        (>= (batteryLevel)(* (distance ?l1 ?l2)(cost-per-distance)))
                    )
        :effect(and(taxiAt ?l2)
                    (not(taxiAt ?l1))
                    (increase (total-cost)(distance ?l1 ?l2))      
                    (decrease (batteryLevel)(* (distance ?l1 ?l2) (cost-per-distance)))
                    (when (congested ?l2)
                        (increase (total-cost)(* 2 (distance ?l1 ?l2))
                    ))
                )
    )
    (:action recharge
        :parameters(?l - location)
        :precondition(and(taxiAt ?l)
                        (rechargeStation ?l)
                    )
        :effect(and(increase (batteryLevel) 100)
                    (increase (total-cost) 10)
        )
                
    )
    (:action pickUp
        :parameters(?p - passenger ?l - location)   
        :precondition(and(requestFrom ?p ?l) 
                        (passengerAt ?p ?l)
                        (taxiAt ?l)
                        (forall(?p1 - passenger)(not(onTaxi ?p1)))                            
                    ) 
        :effect(and(not(passengerAt ?p ?l))
                    (onTaxi ?p)
                    (not(requestFrom ?p ?l))
                )
    )
    (:action getOff
        :parameters(?p - passenger ?l - location)
        :precondition(and(onTaxi ?p)
                        (taxiAt ?l)
                        (requestTo ?p ?l)
                    )
        :effect(and(not(onTaxi ?p))
                    (passengerAt ?p ?l)
                    (not (requestTo ?p ?l))
                )
    )

)